FROM node:20-alpine

# Install system dependencies
RUN apk add --no-cache \
    ffmpeg \
    opus \
    yt-dlp \
    python3 \
    build-base \
    g++ \
    make

WORKDIR /app

# Copy package files
COPY data-plane-js/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY data-plane-js/ ./

# Runtime Variables
ENV NODE_ENV=production
ENV REDIS_URL=redis://redis:6379

CMD ["npm", "start"]
